= Technology Entrepreneurship Education

_Keywords:_ technology entrepreneurship, educational robotics, entrepreneurship, innovation, Arduino workshop, Raspberry Pi Pico, cross-disciplinary

*Technology entrepreneurship* is the interface between the more established academic fields of entrepreneurship and technology based innovation.



== Objectives for the learners

- develop effective problem-solving skills
- decompose problems into smaller parts
- use pseudocode as a tool for sequencing actions
- use existing code with attributes to recognise patterns
- systematically identify and fix bugs
- use conditions and compound conditions to program encoded devices

== Key Objectives

- use decomposition skills to break a complex problem down into smaller parts
- identify and fix programming problems
- develop their ability to recognise patterns and create effective programs
- explore conditional programming
- be able to explain the principle of digital security
- use computational thinking skills to produce a complete solutions to a problem
- create and follow a set of step-by-step pseudocode instructions
- decompose, identify, and fix problems in the pseudo code

== Projects

. monitor temperature
. monitor fan speed
. switch power remotely
. IoT
. process automation
. equipment management
. collecting metrics
. IoT of agriculture
  * agtech
  * food production practices
  * monitoring crops, soil, fields, livestock, storage facilities
  * smart agriculture vehicles, drones, autonomous robots, actuators
  * connected agriculture spaces, smart greenhouses, hydroponics
  * data analytics, visualization, management systems
. thermal camera with Raspberry Pi
. cybersecurity with Raspberry Pi
. Christmas light decoration
. portable security box
. network performance monitor
. Wordpress host
. host an Apache server
. chemical experiments facilitated with electronic microcontrollers (see link:https://doi-org.proxy.bnl.lu/10.1038/s41596-019-0272-1[Nature Protocols])
. systems biology (see link:https://doi-org.proxy.bnl.lu/10.1038/s41598-021-89676-5[Nature Scientific Reports])
. healthcare (see link:https://doi-org.proxy.bnl.lu/10.1038/s41598-021-87177-z[Nature Scientific Reports])
. logistics

== Lesson plan

The following table is taken from link:https://education.lego.com/en-gb/lessons/prime-kickstart-a-business[Kickstart a business (Lego Education)]

[cols="1,1,1,1,1,1,1"]
|===

|
| Prepare
| Engage
| Explore
| Explain
| Elaborate
| Evaluate

| 1. Placing your order
|
|
|
|
|
|

| 2. Out of order
|
|
|
|
|
|

| 3. Track your parcels
|
|
|
|
|
|

| 4. Keep it safe
|
|
|
|
|
|

| 5. Keep it really safe!
|
|
|
|
|
|

| 6. Automate it!
|
|
|
|
|
|

| 7. Back to back
|
|
|
|
|
|

|===

== Notes:

"
Technology entrepreneurship focuses on the commercialization of emerging
products and services based on novel technology inventions in either nascent
or established markets. It is an inherently interdisciplinary field of study
as it is closely related to entrepreneurship as a discipline in terms of
methods and tools, while the context is that of science and engineering.
"

"... the respective researchers have oftentimes neither experience nor interest in entrepreneurial activities as it is not part of their profession and training ..."

"... while engineering education had a clear focus on the development and application of technology without any  relation  to  market  contexts,  entrepreneurship  education  pursued  the  objective  to  create  new products,  services,  and  ultimately  ventures. Technology  entrepreneurship  education  aims  to  bridge this  gap  between  the  disciplines  with  the  objective  to  develop  entrepreneurial  knowledge  and competences along in-depth understanding of technology."

"It is undisputed that context has a major impact on learning outcomes in educational activities of any kind. (...)"

"The  context-dependency  of  educational  specifics  (such  as  the  pedagogical  approach, teaching  activities,  desired  learning  outcomes,  etc.)  deserve  special  attention  when  educational activities that were developed in the context of a specific discipline get transferred to the context of a different discipline."

"pedagogical   specifics   of engineering  education  need  to  be  considered  in  this  alignment  as  the  interdisciplinary  nature  of technology entrepreneurship and related education objectives call for interdisciplinary approaches in the design of suitable pedagogy."

"Engineering education typically assumes a problem-based and application-oriented approach in the design  of  pedagogical  methods. This  is  primarily  due  to  the  requirement  of  application-related understanding and  hands-on  experience  of  engineering  graduates."

"The  introduction  of  entrepreneurship  content  in  engineering  education generates new pedagogical models for achieving desired learning outcomes that can in turn greatly enrich entrepreneurship education."

"An important contextual element of engineering education is the use of laboratories and workshops in the development and application of technical products and systems."

"The use of spaces, e.g. laboratories and workshops, creates a reference to real-world problems and contextualizes learning content and objectives  in  application-oriented  scenarios. This  happens  for  instance  through  the  use  of  novel technical equipment, software development, and exercises in prototype development that mirror the activities and tasks of potential future engineering professions."

"Even more important than the impact of specific spaces is the contact and collaboration of communities of practice related to those spaces. For example, the feedback and support from professional engineers regarding the development of a technical  prototype  creates  an  in-depth  learning  experience for  students that  exceeds  classroom learning."

"The  need  for  professional  input  from  both  the  engineering  and  the entrepreneurship disciplines calls for a close interdisciplinary collaboration of academic staff such as researchers  and  lecturers."

" the introduction of entrepreneurship content and methods in the engineering context leads to a change of education outcomes, such as knowledge, skills and capabilities, but potentially also to entrepreneurial engagement of academic staff that has previously been  unaware  and/or  uninterested  in  entrepreneurship."

" (...) technology  entrepreneurship  plays  a conducive role in universities’ socio-economic engagement, because it offers alternative models for transferring knowledge and technology from academia to society and economy."

-- link:https://link.springer.com/referenceworkentry/10.1007/978-981-13-2262-4_172-1[Technology Entrepreneurship - Enriching Entrepreneurship Education]

link:https://www.youtube.com/watch?v=hbP9SgteURM[Technology Entrepreneurship: Lab to Market (HarvardX and edx.org)]

"... they can freely exchange ideas and network with their fellow ..."

"... designed  to  provide  a  rich  and  supportive environment for learning about entrepreneurship, forming   teams,   starting   companies   and   sharing   lessons learned ..."

"The course is team-taught by instructors with substantial technology  and  business  teaching experience ..."

"Topics that are taught include: "

-- link:https://ieeexplore.ieee.org/abstract/document/1263299[Holistic approach for technology entrepreneurship education in engineering]


== Sources:

* link:https://a-z.lu/primo-explore/fulldisplay?docid=TN_informaworld_s10_1111_jsbm_12514&context=PC&vid=BIBNET&search_scope=All_content&tab=all_content&lang=fr_FR[The Learning Process in Technology Entrepreneurship Education]
* link:https://a-z.lu/primo-explore/fulldisplay?docid=EBOOKMMEBOOKCENTRALANNUALEBC275471&context=L&vid=BIBNET&search_scope=All_content&tab=all_content&lang=fr_FR[Entrepreneurship education]
* link:https://a-z.lu/primo-explore/fulldisplay?docid=EBOOKMMEBOOKCENTRALDDAEBC5982452&context=L&vid=BIBNET&search_scope=All_content&tab=all_content&lang=fr_FR[Entrepreneurship Education : Begriff - Theorie - Verständnis]
* link:https://a-z.lu/primo-explore/fulldisplay?docid=EBOOKMMDOAB43510&context=L&vid=BIBNET&search_scope=All_content&tab=all_content&lang=fr_FR[ The Change Laboratory for Teacher Training in Entrepreneurship Education]
* link:https://a-z.lu/primo-explore/fulldisplay?docid=TN_proquest1848485342&context=PC&vid=BIBNET&search_scope=All_content&tab=all_content&lang=fr_FR[Teaching and research opportunities in technology entrepreneurship]
