= Business 1iec - Revision (2019-20)

{blank} +




== Subtheme 3.1: Business objectives and strategy 

Revision of this subtheme should take you two hours. You can either read the four chapters or watch the tutorial videos. Answering the past paper (task 4) should take 40-45 minutes. +

Remember that the main goal is to be able to use concepts like _Porter's matrix_, _Ansoff's matrix_, _Boston matrix_, ... in the context of a business. Simply memorizing these concepts is not enough. Use the student answer provided in the table below to practice that.

*Note:* Try to use a computer instead of your tablet/smartphone. Especially the past paper links don't work as they should on those devices.


{blank} +


[cols="1,2,4,5", options="header"]
//[%autowidth, options="header"]
|===
|Week |Date |Topic |Coursework


|
| 17/3/2020
| _Corporate objectives_ +
  _Theories of corporate strategy_ +
  _SWOT analysis_ +
  _Impact of external influences_
| *(1)* Revise chapters 44-47 +
  *(2)* Watch the following _tutorial videos_: +
        _(i)_ link:https://www.youtube.com/watch?v=RdQuKwhCzGU[Business objectives (4 min)] +
        _(ii)_ link:https://www.youtube.com/watch?v=CVByJVRWNqs&t=74s[Mission statement (4 min)] +
        _(iii)_ link:https://www.youtube.com/watch?v=uRgQlW4qRTo[Business strategy vs. business tactics (5 min)] +
        _(iv)_ link:https://www.youtube.com/watch?v=CMFXsJxi05U&t=89s[[red]#Ansoff matrix# (14 min)] +
        _(v)_ link:https://www.youtube.com/watch?v=i66HWNCwUTs[[red]#Porter's Generic Strategies# (10 min)] +
        _(vi)_ link:https://www.youtube.com/watch?v=rW5SOENyq5g[[red]#Boston matrix# (15 min)] +
        _(vii)_ link:https://www.youtube.com/watch?v=7JmDXDZYx0s[SWOT analysis (7 min)] +
        _(viii)_ link:https://www.youtube.com/watch?v=sP2sDw5waEU[PESTLE analysis (9 min)] +
        _(ix)_ link:https://www.youtube.com/watch?v=cm9SsMa56r4[Porter's Five Forces Model (21 min)] +
  *(3)* Past papers (student answers): +
        _(i)_ link:https://qualifications.pearson.com/content/dam/pdf/A%20Level/Business%20Studies/2013/Exam%20materials/6BS04_01_pef_20130815.pdf#page=14[Assess Superdry's corporate strategy with the aid of [red]#Porter's strategic matrix#.] +
        _(ii)_ link:https://qualifications.pearson.com/content/dam/pdf/A%20Level/Business%20Studies/2013/Exam%20materials/Examiner-report-Unit-4-(6BS04)-June-2014.pdf#page=11[Assess the likely implications on Greggs' [red]#corporate strategy# of applying VAT to hot takeaway food] +
        _(iii)_ link:https://qualifications.pearson.com/content/dam/pdf/A%20Level/Business%20Studies/2013/Exam%20materials/6BS04_01_pef_20130307.pdf#page=6[Using Ansoff's Matrix , explain Superdry's decision to launch a mobile phone sales option] +
  *(4)* link:https://pastpapers.papacambridge.com/Cambridge%20International%20Examinations%20%28CIE%29/AS%20and%20A%20Level/Business%20%28for%20first%20examination%20in%202016%29%20-%209609/2017%20Nov/9609_w17_qp_32.pdf[Answer question 6 in section B.] +
  link:https://pastpapers.papacambridge.com/Cambridge%20International%20Examinations%20%28CIE%29/AS%20and%20A%20Level/Business%20%28for%20first%20examination%20in%202016%29%20-%209609/2017%20Nov/9609_w17_ms_32.pdf#page=16[[red]#Marking scheme#.]
|===

{blank} +


== Subtheme 3.2: Business growth 

Revision of this subtheme should take you two hours. You can either read the four chapters or watch the tutorial videos. Answering the past paper (task 4) should take 20-30 minutes. +

Remember that the main goal is to be able to use concepts like _economies/diseconomies of scale_, _market power_, _brand recognition_, _profitability_, _overtrading_ ... in an essay-style question. Watch link:https://www.youtube.com/watch?v=B4LMyav5SN0[this video], there are interesting examples and hints for exam questions. You may be asked to evaluate whether growth is beneficial for a business. 

*Note:* Try to use a computer instead of your tablet/smartphone. Especially the past paper links don't work as they should on those devices.



{blank} +


[cols="1,2,4,5", options="header"]
//[%autowidth, options="header"]
|===
|Week |Date |Topic |Coursework

|
| 19/3/2020
| _Growth_ +
  _Mergers and takeovers_ +
  _Organic growth_ +
  _Reasons for staying small_
| *(1)* Revise chapters 48-51 +
  *(2)* Watch the following _tutorial videos_: +
  _(i)_ link:https://www.youtube.com/watch?v=ny29zZmmwkM[Growth Strategy: Internal v External Growth (21 min)] +
  _(ii)_ link:https://www.youtube.com/watch?v=b82S3AFHoE0[Economic Growth (GDP) (4 min)] +
  _(iii)_ link:https://www.youtube.com/watch?v=C0pAxcTgEB4[Constraints on Business Growth (8 min)] +
  _(iv)_ link:https://www.youtube.com/watch?v=uOO4ClVUrkw[Business Growth Strategy - Horizontal and Vertical Integration (6 min)] +
  _(v)_ link:https://www.youtube.com/watch?v=9fUWnZ3k2tc[Business Growth Strategy - Synergy (6 min)] +
  _(vi)_ link:https://www.youtube.com/watch?v=2E1pAqZ8qCg[Economies of Scale (9 min)] +
  _(vi)_ link:https://www.youtube.com/watch?v=s4DGC6yITxQ[Overtrading (5 min)] +
  _(vii)_ link:https://www.youtube.com/watch?v=baN8NrcFaFQ[Takeovers and mergers (28 min)] +
  _(viii)_ link:https://www.youtube.com/watch?v=B4LMyav5SN0[Essay tip: Internal v External Growth (15 min)] +
  *(3)* Read the following student answers: +
  _(i)_ link:https://qualifications.pearson.com/content/dam/pdf/A%20Level/Business%20Studies/2013/Exam%20materials/6BS03_01_pef_20130307.pdf#page=14[Assess the likely consequences for Tata of expanding by mergers and takeovers.(8 marks)] +
  _(ii)_ link:https://qualifications.pearson.com/content/dam/pdf/A%20Level/Business%20Studies/2013/Exam%20materials/6BS03-6EB03-Jan-2010-ER.pdf#page=11[Assess the likely importance of mergers and takeovers in L’Oréal’s international success. (8 marks)] +
  _(iii)_ link:https://qualifications.pearson.com/content/dam/pdf/A%20Level/Business%20Studies/2013/Exam%20materials/6BS03_01_pef_20110309.pdf#page=10[Assess the likely benefits for BAT of expanding by mergers and takeovers. (8 marks)] +
  *(4)* Read link:https://pastpapers.papacambridge.com/Cambridge%20International%20Examinations%20%28CIE%29/AS%20and%20A%20Level/Business%20%28for%20first%20examination%20in%202016%29%20-%209609/2017%20Jun/9609_s17_qp_31.pdf[this extract] and answer the following question: + 
  _Assess the most likely reasons why the takeover of SRH has so far failed to achieve TTC’s objectives. (12 marks)_.

|===

{blank} +

== Research topic: The entertainment industry

Today we will focus on _financing_ in this industry. 

Research on FT how the following companies are financed: +

* Spotify
* Disney
* Cineworld
* Netflix
* BBC

Use the shared document in _Teams_ (saved in "Files" --> "Shared document") to write your findings (in bullet-points). Provide the link to your article in the "References" section.



{blank} +

== Subtheme 3.3: Decision-making techniques 

Revision of this subtheme should take you two hours. You can either read the four chapters or watch the tutorial videos. +

Remember that the main goal is to be able to calculate _ratios_, construct _decision trees_ and calculate the components of the _critical path_ network. At your level the marks assigned to the calculation will be relatively low. The key point is to be able to use these values in an essay-style question. If your calculations are wrong, it will be very difficult to write a consistent essay.

*Note:* Try to use a computer instead of your tablet/smartphone. Especially the past paper links don't work as they should on those devices.



[cols="1,2,4,5", options="header"]
//[%autowidth, options="header"]
|===
|Week |Date |Topic |Coursework

|
| 24/3/2020
| _Quantitative sales forecasting_ +
  _Investment appraisal_ +
  _Decision trees_ +
  _Critical path analysis_
| *(1)* Revise chapters 52-55 +
  *(2)* Watch the following _tutorial videos_: +
  _(i)_ link:https://www.youtube.com/watch?v=C9zJbo6LKo8[Index Numbers (12 min)] +
  _(ii)_ link:https://www.youtube.com/watch?v=kEsZKO87TlU[Payback Period (10 min)] +
  _(iii)_ link:https://www.youtube.com/watch?v=Yl7U7GovOQk[Ratios (27 min)] +
  _(iv)_ link:https://www.youtube.com/watch?v=-ICsKIB6AzI[Average Rate of Return (4 min)] +
  _(v)_ link:https://www.youtube.com/watch?v=2GUVGx2KL-w[Net Present Value (16 min)] +
  _(vi)_ link:https://www.youtube.com/watch?v=PYxDkGlpj_U[Decision Trees (14 min)] +
  _(vii)_ link:https://www.youtube.com/watch?v=poOyKIt7M1g[Critical Path Analysis (11 min)] +
  *(3)* Basic Business Math Knowledge: +
  _(i)_ link:https://www.youtube.com/watch?v=lIuKWV8Ho8E[Calculating Averages (5 min)] +
  _(ii)_ link:https://www.youtube.com/watch?v=QZs8y0Y_3Vk[Calculating Percentage Changes (6 min)] +
  _(iii)_ link:https://www.youtube.com/watch?v=D7ggEPyfuvg[Exchange Rates (6 min)] +
  _(iv)_ link:https://www.youtube.com/watch?v=IKihYinXmIg[[red]#Depreciation# (6 min)] +
  *(4)* Techniques for answering questions: +
  _(i)_ link:https://www.youtube.com/watch?v=OZtstmE89qE[Short _4-mark_ questions (6 min)] +
  _(ii)_ link:https://www.youtube.com/watch?v=oXfIb9o3_7Y[Long _20-mark_ questions (9 min)] 



|===


{blank} +

== Business essay: The global hunt for a coronavirus drug (26/3/2020)

Read the link:https://www.ft.com/content/91bd081e-6e7b-11ea-9bca-bf503995cd6f[following article in the Financial Times]. Answer the following questions and submit in a personal chat *by the end of the lesson*: +

* Discuss the _different strategies_ that the pharma companies adopt in the race for a vaccine or treatment drug? (12 marks)
* Discuss three _main challenges_ that pharma companies face before they can put a product on the market. (12 marks)

These are 12-mark essay questions. Make sure to properly _balance_, _structure_ and _evaluate_ your answers.

{blank} +

== Subtheme 3.4: Influences on business decisions 

Revision of this subtheme should take you two hours. You can either read the four chapters or watch the tutorial videos. +

[cols="1,2,4,5", options="header"]
//[%autowidth, options="header"]
|===
|Week |Date |Topic |Coursework

|
|27/3/2020
|_Corporate influences_ +
 _Corporate culture_ +
 _Shareholders versus stakeholders_ +
 _Business ethics_
|*(1)* Revise chapters 56-59 +
 *(2)* Watch the following _tutorial videos_: +
 _(i)_ link:https://www.youtube.com/watch?v=xChi9_5W-Y8[Key Influences on the Organisational Culture of a Business (7 min)] +
 _(ii)_ link:https://www.youtube.com/watch?v=AJKEmfh8Q3c[Influences on the Choice of Strategic Positioning (5 min)] +
 _(iii)_ link:https://www.youtube.com/watch?v=zKhqN69MT-0[Influences on Financial Objectives (5 min)] +
 _(iv)_ link:https://www.youtube.com/watch?v=MfL_0ko4T3o[Organisational culture (27 min)] +
 _(v)_ link:https://www.youtube.com/watch?v=EK1ak9lXLo8[Business ethics (19 min)] +
 _(vi)_ link:https://www.youtube.com/watch?v=nkteAJBtM9A[Corporate Social Responsibility - CSR (19 min)] +
 *(3)* Multiple choice question in _Microsoft Forms_
|===


== Supply chain during the pandemic (13/3/2020)

Read the following article: link:https://www.ft.com/content/16209002-6531-11ea-a6cd-df28cc3c6a68[Why coronavirus spells trouble for smartphones] and answer the questions, as well as the 20-mark essay, in _Microsoft Teams (Forms)_ . +

== Globalisation (21/4/2020)

* Topics: _globalisation_, _government intervention_, _leadership_
* Watch the video link:https://www.ft.com/video/96240572-7e35-4fcd-aecb-8f503d529354[Macron: coronavirus is Europe's 'moment of truth']