= Computational Tools

:stem: latexmath
:eqnums:

You can use the following websites to run your (R, julia, Rust) code online, without having to install anything:

* link:https://rextester.com/l/r_online_compiler[Compile R codes online]
* link:https://www.tutorialspoint.com/execute_julia_online.php[Execute Julia code online]
* link:https://www.tutorialspoint.com/compile_rust_online.php[Execute Rust code online]


== Slice sampler

This part is taken from link:https://www.springer.com/gp/book/9780387212395[Robert and Casella (2004)].

At iteration _t_, simulate:

\begin{eqnarray}
 u^{(t+1)} &\sim& U_{[0,f(x^{(t)}]} \nonumber \\
 x^{(t+1)} &\sim& U_{A^{(t+1)}} \nonumber 
\end{eqnarray}
with $A^{(t+1)} = \{ x: f(x) \geq u^{(t+1)} \}$


=== Example 1

In this example, the _slice sampler_ will be used to simulate from the density:
\[
f(x)=\frac{1}{2}\exp( -\sqrt{x} )
\]

At iteration _t_, simulate: 
\begin{eqnarray}
 u^{(t+1)} &\sim& U_{[0,\frac{1}{2}\exp( -\sqrt{x} )]} \nonumber \\
 x^{(t+1)} &\sim& U_{[0,(-\log(2u))^2]} \nonumber 
\end{eqnarray}

Using *R*

[source,R]
----
# Sample from 0.5*exp(-sqrt(x))
# using the slice sampler

f <- function(y)exp(-sqrt(y))/2;

nsim <- 50000;

x <- array(0,dim=c(nsim,1));
x[1] <- -log(runif(1));

for (i in 2:nsim)  {
     w <- runif(1,min=0,max=f(x[i-1]));
     x[i] <- runif(1,min=0,max=(-log(2*w))^2);
}

hist(x,main="Slice sample",xlim=c(0,60),ylim=c(0,.25),freq=F,col="green",breaks=250)

par(new=T)

plot(function(y)f(y), 0, 70, xlim=c(0,60),ylim=c(0,.25),xlab="",ylab="",xaxt="n",yaxt="n",lwd=3)

----


Using *julia*

[source,julia]
----

using Random, Distributions

# Setting the seed
Random.seed!(123) 

function f(y)
    exp( -sqrt(y) ) / 2
end

nsim = 50000

x = rand(Uniform(0.0,1.0),nsim,1)

x[1] = -log.( rand(Uniform(0.0,1.0)) )

for i in 2:nsim
    w = rand(Uniform(0.0,f(x[i-1])))
    x[i] = rand(Uniform(0.0,(-log.(2*w))^2))
end

# Histogram of density
using Plots; pyplot()
Plots.PyPlotBackend()
histogram(x)

----


=== Example 2
Now we consider a truncated normal distribution $\mathcal{N}$(3,1), which is restricted to the interval [0,1]. 

In this example, the _slice sampler_ will be used to simulate from the density:
[stem]
++++
f(x) \varpropto f_1(x) = \exp\big( -(x+3)^2/2 \big) \mathbb{1}_{[0,1]}{(x)}
++++



At iteration _t_, simulate: 
\begin{eqnarray}
 u^{(t+1)} &\sim& \exp\big( -(x+3)^2/2 \big) U_{[0,1]} \nonumber \\
 x^{(t+1)} &\sim& U_{[0,(-3+\sqrt{-2\log(u)})]} \nonumber
\end{eqnarray}


[source,R]
----

# Sample from a N(-3,1) truncated to [0,1]
# using the slice sampler

nsim = 1000

obs <- matrix(0,nsim,2)
obs[1,1] = .25
obs[1,2] = 0.5*exp(-0.5*(obs[1,1]+3)^2)

for (i in 2:nsim){
 obs[i,2] = exp(-0.5*(obs[i-1,1]+3)^2)*runif(1)
 obs[i,1] = runif(1)*min(1,-3+sqrt(-2*log(obs[i,2])))
 }
    
hist(obs,main="Slice sample",freq=F,col="green", breaks=25)

----



== Monte Carlo Integration

Consider the function,
\begin{eqnarray}
  h(x) = [ \cos(50x) + \sin(20x) ]^2 \nonumber
\end{eqnarray}

The integral,
\begin{eqnarray}
  \int^1_0 h(x) dx \nonumber
\end{eqnarray}
can be calculated by generating
\[
   U_1, U_2, \ldots, U_n  \sim  iid \quad U(0,1) 
\]
random variables, and approximate $\int h(x) dx$ with
\[
   \sum^n_{i=1} h(U_i)/n
\]

Using *R*

[source,R]
----

nsim <- 10000;
u <- runif(nsim);
den <- 1:(nsim)

# The function to be integrated
mci.ex <- function(x){(cos(50*x)+sin(20*x))^2}
par(mfrow=c(1,3))
plot(function(x)mci.ex(x), xlim=c(0,1),ylim=c(0,4),xlab="Function",ylab="")
    
# The Monte Carlo sum
## Generated Values of Function
hint <- mci.ex(u)
## Mean
hplot <- cumsum(hint)/den
## Standard Errors
stdh <- sqrt( cumsum(hint^2)/den - (hplot)^2)
upper <- hplot+stdh/sqrt(den)
lower <- hplot-stdh/sqrt(den)

----


== Simulated Annealing

Given a _temperature_ parameter $T>0$, a sample $\theta^T_1, \theta^T_2, \ldots$ is generated from the distribution
\[
 \pi(\theta) \varpropto \exp( h(\theta)/T ) 
\]


=== Example 3

We are searching for the maximum of the following function
\[
  h(x) = [ \cos(50x) + \sin(20x) ]^2
\]
Note: Variable 

At iteration _t_ the algorithm is at $( x^{(t)},h^{(t)} )$:

. Simulate $u \sim U(a_t, b_t)$ where $a_t = \max( x^{(t)}-r,0 )$ and $b_t = \min( x^{(t)}+r,1 )$
. Accept $x^{(t+1)}=u$ with probability
\[
  \rho^{(t)} = \min \big\{  \exp \big(  \frac{h(u)-h(x^{(t)})}{T_t} \big), 1  \big\}
\]
take $x^{(t+1)}=x^{(t)}$ otherwise.
. Update $T_t$ to $T_{t+1}$

[source,R]
----

par(mfrow=c(1,2))

# The function to be optimized
mci <- function(x){(cos(50*x)+sin(20*x))^2}

# The Monte Carlo maximum
nsim <- 2500
u <- runif(nsim)

# Simulated annealing
xval <- array(0,c(nsim,1));
r <- .5
for(i in 2:nsim){
    test <- runif(1, min=max(xval[i-1]-r,0),max=min(xval[i-1]+r,1));
    delta <- mci(test) - mci(xval[i-1]);
    rho <- min(exp(delta*log(i)/1),1);
    xval[i] <- test*(u[i]<rho)+xval[i-1]*(u[i]>rho)
}
mci(xval[nsim])

# Plot the trajectory of the optimization path
plot(function(x)mci(x), xlim=c(0,1),ylim=c(0,4),xlab="Function",ylab="")
plot(xval,mci(xval),type="l",lwd=2)
 

----


== Metropolis-Hastings Algorithm

Let $q(\theta, \vartheta)$ be a _proposal density_ or a _candidate-generating density_ (link:http://www2.stat.duke.edu/~scs/Courses/Stat376/Papers/Basic/ChibGreenberg1995.pdf[Chib and Greenberg, 1995]) such that
\[
 \int q(\theta, \vartheta) d\vartheta = 1
\]
Also let $U(O, 1)$ denote the uniform distribution over $(0, 1)$. Then, a general version of the Metropolis- Hastings algorithm for sampling from the posterior distribution $\pi(\theta,D)$ can be described as follows:

. Choose an arbitrary starting point $\theta_0$ and set $i=0$.
. Generate a candidate point $\theta^*$ from $q(\theta_i,\cdot)$ and $u$ from $U(0,1)$.
. Set $\theta_{i+1}=\theta^*$ if $u \leq a(\theta_i, \theta^*)$ and $\theta_{i+1}=\theta_i$ otherwise, where the acceptance probability is given by
\[
 a(\theta,\vartheta) = \min\big\{ 
                        \frac{ \pi(\vartheta|D)q(\vartheta, \theta) }{ \pi(\theta|D)q(\theta, \vartheta) },
                        1
                        \big\}
\]
. Set $i=i+1$, and go to Step 2.

=== Example 4

Let us consider the following simple linear model:
\[
 y_t = \alpha x_t + \beta + \epsilon_t
\]
where $\epsilon \sim N(0, \sigma^2)$.




_Source_: R code taken from link:https://theoreticalecology.wordpress.com/2010/09/17/metropolis-hastings-mcmc-in-r/[A simple Metropolis-Hastings MCMC in R]

[source,R]
----

### Creating test data
trueA <- 5
trueB <- 0
trueSd <- 10
sampleSize <- 31
 
# create independent x-values 
x <- (-(sampleSize-1)/2):((sampleSize-1)/2)
# create dependent values according to ax + b + N(0,sd)
y <-  trueA * x + trueB + rnorm(n=sampleSize,mean=0,sd=trueSd)
 
plot(x,y, main="Test Data")


### Deriving the likelihood
likelihood <- function(param){
    a = param[1]
    b = param[2]
    sd = param[3]
     
    pred = a*x + b
    singlelikelihoods = dnorm(y, mean = pred, sd = sd, log = T)
    sumll = sum(singlelikelihoods)
    return(sumll)   
}
 
# Example: plot the likelihood profile of the slope a
slopevalues <- function(x){return(likelihood(c(x, trueB, trueSd)))}
slopelikelihoods <- lapply(seq(3, 7, by=.05), slopevalues )
plot (seq(3, 7, by=.05), slopelikelihoods , type="l", xlab = "values of slope parameter a", ylab = "Log likelihood")


### Defining the prior
# Prior distribution
prior <- function(param){
    a = param[1]
    b = param[2]
    sd = param[3]
    aprior = dunif(a, min=0, max=10, log = T)
    bprior = dnorm(b, sd = 5, log = T)
    sdprior = dunif(sd, min=0, max=30, log = T)
    return(aprior+bprior+sdprior)
}

### Defining the posterior
posterior <- function(param){
   return (likelihood(param) + prior(param))
}



######## Metropolis algorithm ################
 
proposalfunction <- function(param){
    return(rnorm(3,mean = param, sd= c(0.1,0.5,0.3)))
}
 
run_metropolis_MCMC <- function(startvalue, iterations){
    chain = array(dim = c(iterations+1,3))
    chain[1,] = startvalue
    for (i in 1:iterations){
        proposal = proposalfunction(chain[i,])
         
        probab = exp(posterior(proposal) - posterior(chain[i,]))
        if (runif(1) < probab){
            chain[i+1,] = proposal
        }else{
            chain[i+1,] = chain[i,]
        }
    }
    return(chain)
}
 
startvalue = c(4,0,10)
chain = run_metropolis_MCMC(startvalue, 10000)
 
burnIn = 5000
acceptance = 1-mean(duplicated(chain[-(1:burnIn),]))


### Summary: #######################
 
par(mfrow = c(2,3))
hist(chain[-(1:burnIn),1],nclass=30, , main="Posterior of a", xlab="True value = red line" )
abline(v = mean(chain[-(1:burnIn),1]))
abline(v = trueA, col="red" )
hist(chain[-(1:burnIn),2],nclass=30, main="Posterior of b", xlab="True value = red line")
abline(v = mean(chain[-(1:burnIn),2]))
abline(v = trueB, col="red" )
hist(chain[-(1:burnIn),3],nclass=30, main="Posterior of sd", xlab="True value = red line")
abline(v = mean(chain[-(1:burnIn),3]) )
abline(v = trueSd, col="red" )
plot(chain[-(1:burnIn),1], type = "l", xlab="True value = red line" , main = "Chain values of a", )
abline(h = trueA, col="red" )
plot(chain[-(1:burnIn),2], type = "l", xlab="True value = red line" , main = "Chain values of b", )
abline(h = trueB, col="red" )
plot(chain[-(1:burnIn),3], type = "l", xlab="True value = red line" , main = "Chain values of sd", )
abline(h = trueSd, col="red" )
 
# for comparison:
summary(lm(y~x))

----